#!/usr/bin/env python3
"""Build the plugin ZIPs and regenerate everything derived from them.

One command keeps three things in sync that used to be maintained by hand and had
already drifted apart:

  plugins/<name>.zip   built from the plugin's source directory
  plugins.xml          the QGIS custom-repository feed
  index.html           the plugin cards on https://plugins.qgis.ge

Versions, names, descriptions and the QGIS compatibility range always come from each
plugin's own metadata.txt. tools/plugins.json only carries what metadata.txt has no
place for: the source directory, the ZIP name, and the presentation copy for the site.

    python tools/build.py            # rebuild zips + plugins.xml + index.html
    python tools/build.py --check    # verify everything is in sync, change nothing
"""

from __future__ import annotations

import argparse
import configparser
import fnmatch
import io
import json
import os
import re
import sys
import zipfile
from xml.sax.saxutils import escape, quoteattr

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "tools", "plugins.json")
PLUGINS_DIR = os.path.join(ROOT, "plugins")
PLUGINS_XML = os.path.join(ROOT, "plugins.xml")
INDEX_HTML = os.path.join(ROOT, "index.html")

SKIP_DIRS = {"__pycache__", ".git", ".venv", "venv", "node_modules", ".pytest_cache"}
SKIP_EXTS = {".pyc", ".pyo", ".pyd"}

# Fixed timestamp so rebuilding without source changes produces a byte-identical zip
# and git stays quiet.
ZIP_DATE = (1980, 1, 1, 0, 0, 0)

SITE_MARKER_START = "/* ==== generated by tools/build.py — do not edit by hand ==== */"
SITE_MARKER_END = "/* ==== end generated ==== */"


# --------------------------------------------------------------------------- metadata


def parse_metadata(text: str) -> dict:
    parser = configparser.RawConfigParser(strict=False)
    parser.optionxform = str  # metadata.txt keys are camelCase (qgisMinimumVersion)
    parser.read_string(text)
    return dict(parser["general"])


def read_metadata(plugin: dict) -> dict:
    if plugin.get("source"):
        path = os.path.join(ROOT, plugin["source"], "metadata.txt")
        with open(path, encoding="utf-8") as fh:
            return parse_metadata(fh.read())
    # vendored: the zip built in another repository is authoritative
    zip_path = os.path.join(PLUGINS_DIR, plugin["zip"])
    with zipfile.ZipFile(zip_path) as zf:
        name = f"{plugin['folder']}/metadata.txt"
        return parse_metadata(zf.read(name).decode("utf-8"))


def first_line(value: str) -> str:
    """metadata.txt values can span indented continuation lines; take the first."""
    return value.strip().splitlines()[0].strip() if value.strip() else ""


# --------------------------------------------------------------------------- zips


def collect_files(source_dir: str, excludes: list[str]):
    for dirpath, dirnames, filenames in os.walk(source_dir):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            abs_path = os.path.join(dirpath, name)
            rel = os.path.relpath(abs_path, source_dir).replace("\\", "/")
            if os.path.splitext(name)[1] in SKIP_EXTS:
                continue
            if any(fnmatch.fnmatch(rel, pat) for pat in excludes):
                continue
            yield abs_path, rel


def build_zip(plugin: dict) -> bytes:
    source_dir = os.path.join(ROOT, plugin["source"])
    folder = plugin["folder"]
    excludes = plugin.get("exclude", [])
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for abs_path, rel in collect_files(source_dir, excludes):
            info = zipfile.ZipInfo(f"{folder}/{rel}", date_time=ZIP_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            with open(abs_path, "rb") as fh:
                zf.writestr(info, fh.read())
    return buf.getvalue()


# --------------------------------------------------------------------------- outputs


def download_url(base_url: str, zip_name: str, version: str) -> str:
    # ?v= busts the Cloudflare cache when a plugin is re-released under the same name
    return f"{base_url}/plugins/{quote_path(zip_name)}?v={version}"


def quote_path(value: str) -> str:
    return value.replace(" ", "%20")


def render_xml(entries: list[dict], repo: dict) -> str:
    out = ['<?xml version="1.0" encoding="UTF-8"?>', "<plugins>"]
    for e in entries:
        md = e["metadata"]
        out.append(
            f'  <pyqgis_plugin name={quoteattr(md["name"])} version={quoteattr(md["version"])}>'
        )

        def tag(name, value):
            if value:
                out.append(f"    <{name}>{escape(str(value))}</{name}>")

        tag("description", first_line(md.get("description", "")))
        tag("about", first_line(md.get("about", "")))
        tag("version", md["version"])
        tag("qgis_minimum_version", md.get("qgisMinimumVersion", ""))
        tag("qgis_maximum_version", md.get("qgisMaximumVersion", ""))
        tag("homepage", md.get("homepage", repo["homepage"]))
        out.append(f'    <file_name>{escape(e["plugin"]["zip"])}</file_name>')
        tag("download_url", e["download_url"])
        if e.get("icon_url"):
            tag("icon", e["icon_url"])
        tag("author_name", md.get("author", ""))
        tag("email", md.get("email", ""))
        tag("tracker", md.get("tracker", ""))
        tag("repository", md.get("repository", repo["homepage"]))
        tag("tags", md.get("tags", ""))
        tag("experimental", md.get("experimental", "False"))
        tag("deprecated", md.get("deprecated", "False"))
        out.append("  </pyqgis_plugin>")
    out.append("</plugins>")
    return "\n".join(out) + "\n"


def render_site_block(entries: list[dict]) -> str:
    rows = []
    for e in entries:
        md = e["metadata"]
        site = e["plugin"]["site"]
        rows.append(
            {
                "id": e["plugin"]["id"],
                "name": md["name"],
                "ka_name": site["ka_name"],
                "version": md["version"],
                "status": site["status"],
                "zip": os.path.basename(e["download_url"]),
                "emoji": site["emoji"],
                "featured": site["featured"],
                "qgis_min": md.get("qgisMinimumVersion", ""),
                "qgis_max": md.get("qgisMaximumVersion", ""),
                "en": site["en"],
                "ka": site["ka"],
                "tags": site["tags"],
            }
        )
    body = json.dumps(rows, ensure_ascii=False, indent=1)
    return f"{SITE_MARKER_START}\nconst PLUGINS={body};\n{SITE_MARKER_END}"


def replace_site_block(html: str, block: str) -> str:
    pattern = re.compile(
        re.escape(SITE_MARKER_START) + r".*?" + re.escape(SITE_MARKER_END), re.S
    )
    if pattern.search(html):
        return pattern.sub(lambda _m: block, html)
    # first run: swap the hand-written array for a marked, generated one
    legacy = re.compile(r"const PLUGINS=\[.*?\n\];", re.S)
    if not legacy.search(html):
        raise SystemExit("index.html: found neither the generated markers nor const PLUGINS=[…]")
    return legacy.sub(lambda _m: block, html)


# --------------------------------------------------------------------------- driver


def write_if_changed(path: str, data, check: bool, changed: list[str]) -> None:
    binary = isinstance(data, bytes)
    mode = "rb" if binary else "r"
    kwargs = {} if binary else {"encoding": "utf-8", "newline": ""}
    current = None
    if os.path.exists(path):
        with open(path, mode, **kwargs) as fh:
            current = fh.read()
    if current == data:
        return
    changed.append(os.path.relpath(path, ROOT).replace("\\", "/"))
    if check:
        return
    with open(path, "wb" if binary else "w", **({} if binary else {"encoding": "utf-8", "newline": ""})) as fh:
        fh.write(data)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="report what is out of date, write nothing")
    args = ap.parse_args()

    manifest = json.load(open(MANIFEST, encoding="utf-8"))
    repo = manifest["repository"]
    base_url = repo["base_url"].rstrip("/")

    entries = []
    changed: list[str] = []

    for plugin in manifest["plugins"]:
        metadata = read_metadata(plugin)
        version = metadata["version"]

        if plugin.get("source"):
            payload = build_zip(plugin)
            write_if_changed(os.path.join(PLUGINS_DIR, plugin["zip"]), payload, args.check, changed)
        elif not os.path.exists(os.path.join(PLUGINS_DIR, plugin["zip"])):
            raise SystemExit(f"{plugin['id']}: vendored zip plugins/{plugin['zip']} is missing")

        icon_url = None
        icon = metadata.get("icon", "").strip()
        if icon and plugin.get("source"):
            icon_url = f"{base_url}/{quote_path(plugin['source'])}/{quote_path(icon)}"

        entries.append(
            {
                "plugin": plugin,
                "metadata": metadata,
                "download_url": download_url(base_url, plugin["zip"], version),
                "icon_url": icon_url,
            }
        )

    write_if_changed(PLUGINS_XML, render_xml(entries, repo), args.check, changed)

    with open(INDEX_HTML, encoding="utf-8", newline="") as fh:
        html = fh.read()
    write_if_changed(INDEX_HTML, replace_site_block(html, render_site_block(entries)), args.check, changed)

    for e in entries:
        md = e["metadata"]
        vendored = " (vendored)" if e["plugin"].get("vendored") else ""
        print(
            f"  {md['name']:<22} {md['version']:<8} "
            f"QGIS {md.get('qgisMinimumVersion', '?')}–{md.get('qgisMaximumVersion', '?')}{vendored}"
        )

    if args.check:
        if changed:
            print("\nout of date: " + ", ".join(changed))
            print("run: python tools/build.py")
            return 1
        print("\nup to date")
        return 0

    print("\n" + (f"wrote: {', '.join(changed)}" if changed else "nothing changed"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
